== Kubernetes 概述

分布式容器管理工具。
提供了 *PaaS* 产品共有的普适功能。
Kubernetes 默认解决方案都是可选和可插拔的，可以自定义灵活选择。

=== Kubernetes 功能

* 集群**垂直扩容**
+
新的服务器**节点**可以很容易的进行增加和删除。

* 应用**水平扩容**
+
**容器实例**能通过__副本控制器__进行轻松的扩容、缩容。

* **弹性伸缩**
+
根据**容器**资源使用情况，进行自动的扩缩容。

* **服务发现**和**负载均衡**
+
为**容器**提供 DNS 解析或 IP 地址暴露；为**容器**流量进行负载均衡。

* *存储编排*
+
允许自动挂载选择的存储系统（例如本地存储、NFS、GFS、Ceph、公有云等）。

* **自动部署**和**回滚**
+
可以使用 Kubernetes 描述已部署容器的所需状态，它可以以**受控的速率**将实际状态更改为期望状态；如果应用部署出现错误，可以实现**自动回滚**。

* *自动完成装箱计算*
+
允许指定**容器**所需的 CPU 和 RAM 资源，更好的管理容器的资源使用。

* *自我修复*
+
将**重启**启动失败的容器、**替换**容器、**杀死**不响应用户定义的运行状况检查的容器，并且在准备好容器服务之前不对外提供服务。

* *密钥与配置管理*
+
允许**存储和管理**敏感信息（例如密码、 OAuth 令牌和 SSH 密钥）；支持在不重启容器情况下**部署和更新密钥**。

=== Kubernetes 集群角色与组件

Kubernetes 集群构建在多台主机上， Kubernetes 集群内节点被划分为两类角色：

* 主节点(Master) / 控制平面(Control Plane):
+
负责管理集群；负责管理节点以及节点内运行的 Pod ，因此也被称为控制平面。

* 工作节点(Node) / 数据平面(Data Plane)
+
负责维护运行应用 Pod 并提供 Kubernetes 运行环境；

* 附件扩展(Addons)
+
扩展 Kubernetes 集群功能

[plantuml, format="svg", id="role-component"]
-----
@startuml
actor "kubectl" #YELLOW

node Master #E1D5E7 {
    rectangle "ControlPlane" #FA6800 {
        component "kube-apiserver"
        component "kube-scheduler"
        component "kube-controller-manager"
        database "etcd"
    }
    rectangle "Addons" #FAD7AC {
        component "coreDNS"
        component "network"
        component "Dashboard"
    }
}

cloud "Cloud API" #CDEB8B

node Node #D5E8D4 {
    rectangle "DataPlane" #B0E3E6 {
        component "kubelet"
        component "kube-proxy"
        component "container-runtime" #B1DDF0 {
            rectangle "Pod" #00FF00 {
                component "Container" #6D8764
            }
        }
    }
}

"kubectl" == "kube-apiserver" #E51700
"Cloud API" == "kube-proxy" #1BA1E2

"kube-apiserver" .. "etcd"
"kube-apiserver" . "kube-scheduler"
"kube-apiserver" .. "kube-controller-manager"

"kube-apiserver" ... "kubelet" : "watch"

"kubelet" .. "Container"
"kube-proxy" .. "Pod"
@enduml
-----

image:./components-of-kubernetes.svg[Kubernetes 集群的组件]

[TIP]
====
在生产环境中，**控制平面**通常跨多台计算机运行，一个集群通常运行多个节点，提供容错性和高可用性。
====

==== 主节点 Master / 控制平面 Control Plane

* ``kube-apiserver``
+
**API Server** 是控制平面组件，负责公开 Kubernetes API 。
AIP 服务器是 Kubernetes 控制平面的**前端**，所有的组件必须通过 **API Server** 实现交互。
+
Kubernetes API 服务器的主要实现是 ``kube-apiserver`` 。
`kube-apiserver` 支持水平扩展，即可以通过部署多个示例来进行扩缩，并在这些实例之间平衡流量；支持对客户端身份验证。

* ``kube-scheduler``
+
`kube-scheduler` 负责监视新创建的、未指定运行节点(node)的 Pod(表示集群上一组正在运行的容器) ，并选择节点来让 Pod 在上面运行。
+
调度决策考虑的因素包括单个 Pod 及 Pod 集合的资源需求、软硬件及策略约束、亲和性及反亲和性规范、数据位置、工作负载的干扰及最后时限。

* ``kube-controller-manager``
+
`kube-controller-manager` 负责运行**控制器**进程。
控制器通过 **API Server** 监控集群当前 Pod 状态(``status``)，致力于使得 Pod 的当前状态(``status``)与期望状态(``spec``)一致。
+
从逻辑上讲，每个控制器都是一个单独的进程，但是为了降低复杂性，它们都被编译到同一个可执行文件，并在同一个进程中运行。
+
控制器类型：

** 节点控制器 (Node Controller): 负责在节点出现故障时运行通知和响应
** 任务控制器 (Job Controller): 监测代表一次性任务的 Job 对象，然后创建 Pod 来运行这些任务直到完成
** 端点分片控制器 (EndpointSlice Controller): 填充端点分片 (EndpointSlice) 对象（以提供 Service 和 Pod 之间的链接）
** 服务账号控制器 (ServiceAccount Controller): 为新的命名空间创建默认的服务账号(ServiceAccount)

* ``etcd``
+
一致且高可用的键值存储，用作 Kubernetes 所有集群数据的后台数据库。
+
如果 Kubernetes 集群使用 etcd 作为后台数据库，请确保针对这些数据有一份link:[备份]计划。

==== 工作节点 Node / 数据平面 Data Plane

* ``kubelet``
+
`kubelet` 是在集群中每个节点(Node)上运行的代理程序。
+
`kubelet` 接收一组 **API Server** 提供给它的 *PodSpecs* ，**确保这些 PodSpecs 中描述的容器处于运行状态且健康**。
+
[TIP]
`kubelet` **不会管理**不是由 Kubernetes 创建的容器。

* ``kube-proxy``
+
`kube-proxy` 是集群中每个节点(Node)上所运行的网络代理，实现 Kubernetes 服务(Service)概念的一部分。
+
`kube-proxy` 维护每台节点上的一些网络规则(Iptables/IPVS 规则创建喝删除)，控制集群内部或外部的网络会话与 Pod 进行网络通信，并可以支持负载均衡。

* ``container-runtime``

容器运行环境是负责运行容器的软件(`containerd` `CRI-O` 等任何符合 Kubernetes CRI(容器运行环境接口) 的实现)。

==== Addons 附件

===== 服务发现

* ``CoreDNS``
+
可以让 Pod 通过域名被访问；负责管理 Pod IP 与域名之间的关联关系。

===== 联网与网络策略

* ``Flannel``
* ``Calico``

===== 可视化管理

* ``Dashboard``
+
Kubernetes 集群图形化管理界面。

===== 基础设施

* ``KubeVirt``
