= 数字信号处理
Hui.Liu <mexn-0808@outlook.com>
:toc: left
:toclevels: 5
:toc-title: 目录

== 1. 计算机测量仪器系统

=== 计算机测量仪器

**计算机测量仪器**(虚拟仪器)是通过计算机作为仪器主体。
传感器经过放大和信号采集后，通过数据总线传输到计算机中，再由计算机软件进行分析、显示。

=== A/D 转换(ADC)

A/D 转换即模数转换，将模拟信号转换成数字信号。

ADC 类型：

* 积分型
* 逐次逼近型
* 并行比较型
* 串并型

ADC 主要参数：

. 转换器位数(精度)
. 转换时间(采样频率)
. 电压输入范围： `0~5v` `0~10v` `+/-5v` `+/-10v`

=== D/A 转换(DAC)

D/A 转换即数模转换，将数字信号转换成模拟信号。

DAC 主要参数：

. 转换器位数(精度)
. 转换时间(频率)
. 电压输出范围： `0~5v` `0~10v` `+/-5v` `+/-10v`

=== 采样定理

在计算机化测量系统中，**采样**就是将连续的传感器模拟信号，通过 ADC 转换为计算机能够分析的离散数字量。

**采样**是将离散**脉冲序列**与信号**相乘**，取离散点值的过程：

``p(t) * x(t)``

* 脉冲信号 p(t)
* 连续信号 x(t)

采样定理(Nyquist-Shannon)：
为保证采集后信号能真实地保留原始模拟信号信息，信号采样频率必须至少为原信号中最高频率成分的 2 倍，即 ``Fs > 2 Fmax`` 。

在工程领域，为保证采样信号质量： ``Fs > 5 Fmax``

[TIP]
--
**采样过程中的频率混叠**

频率混叠是采样频率不满足采样定理时，信号中的高频成分被不正确的采样成低频成分。

频率混叠是信号离散采样所引起的一个特有现象和重要概念。

例如： 1.5KHz 采样频率对 2KHz 的正弦信号进行采样时，输出是一个 500Hz 正弦信号。
--

当采样信号没有发生频率混叠时，采样信号频谱不发生重叠；
当采样信号发生频谱混叠时，采样信号频谱发生重叠。

在实际工程应用中为了放置发生频率混叠，通常在 ADC 采样前添加**低通滤波器(``0~Fs/2``)**实现添加抗混迭滤波。

.Example: 声卡采集信号——AD变换
[source,matlab]
--
Fs = 11025;             % 采样频率
N= 44100;               % 采样长度
t = [0:N-1]/N;          % 采样时长
x = wavrecord(N, Fs);   % 声卡采样
plot(t, x);             % 图形绘制
set(gca,'color',[0.95, 0.95, 0.95]);
--

.Example: 声卡食输出标准信号——DA变换
[source,matlab]
--
Fs = 44100;                             % 信号采样频率
dt = 1.0 / Fs;                          % 采样间隔
T = 2;                                  % 采样时长
N = T / dt;                             % 采样点数
t = [0: N - 1]/N;                       %
x = 0.3*sin(2*pi*600*t);                % 按照采样点数生成 600Hz 正弦信号
plot(t,x);                              %
axis([0, 0.01, -0.5, 0.5]);             % 绘制波形
wavplay(x,Fs);                          %
set(gca,'color',[0.95,0.95,0.95]);      %
--

== 2. 信号函数与标准信号

信号发生器是一种产生电信号的仪器，按信号波形或函数可分为正弦波信号、方波信号、三角波信号、脉冲信号和随机噪声信号等。

=== 信号函数与标准信号

==== 正弦波

正弦波是一种单一频率成分的基本信号，在后续信号的频谱分析理论中将会学到，任何复杂信号都可以看成一组不同频率、幅值、相位的正弦波信号的组合。

``y(t)=Asin(2πft+φ)``

. A 幅值
. f 频率
. φ 初始相位

正弦波的离散采样公式： ``y(nΔt) = Asin(2πfnΔt+φ)``

. Fs = 1 / Δt
. n = 0,1,2,...,N

.离散采样案例：
[source,matlab]
--
Fs = 11025;
a = 10;
f = 50;
q = 60;
T = 1;
dt = 1.0/Fs;
N = T/dt;
t = linspace(0,T,N);
y = a*sin(2*pi*f*t+q);
plot(x,y);
--

应用实例： DTMF信令(Dual Tone Multi-Frequency)

DTMF 双音多频信号是电话系统中电话机与交换机之间的一种用户信令，通常用于发送被叫号码

应用案例： 摩尔电码

==== 方波

[math,file="math.svg"]
--
y(t)=\begin\{cases}
A, \quad & 0 > t \ge T/2 \\
-A,\quad & -T/2 > t \ge 0
\end\{cases}
--

离散采样公式：

[source]
----
y(nΔt)= ...
Fs = 1/Δt, n = 0,1,2,...,N
----

方波信号函数：

* ``square(t)``
** 频率：``t``
** 占空比(默认：``50%``)
* ``square(t, duty)``

.方波信号
[source,matlab]
--
Fs=11025;
f = 5;                              % 频率
T= 1;
dt = 1.0/Fs;
N = T/dt;
t = linspace(0,T,N);
y1 = square(2*pi*f*t);              % 默认 50% 占空比
y2 = square(2*pi*f*t,75);           % 设置 75% 占空比
plot(t,y1);
hold on;
plot(t,y2);
--

==== 三角波

[math,file="math.svg"]
--
y(t)=\begin\{cases}
A - 2A*2t/T, \quad & 0 > t > T/2 \\
-A+2A*2(t-T/2)/T,\quad & T/2 < t < T
\end\{cases}
--

离散采样公式：

[source]
--
y(nΔt)= ...
Fs = 1/Δt, n = 0,1,2,...,N
--

==== 锯齿波

[math,file="jcb.svg"]
--
\begin{align}
\ y(t) = -A + 2A*t/T  ,\quad & 0 > t > T
\end{align}
--

离散采样公式：

[source]
--
y(nΔt)= ...
Fs = 1/Δt, n = 0,1,2,...,N
--

Matlab函数：

* ``sawtooth(t)``
* ``sawtooth(t,width``

.锯齿波与三角波
[source,matlab]
--
Fs=11050;
f=4;
T=1;
dt = 1.0/Fs;
N=T/dt;
t=linspace(0,T,N);
y1=sawtooth(2*pi*f*t);
y2=sawtooth(2*pi*f*t,1/2);
y3=sawtooth(2*pi*f*t,0);
plot(t,y1);
hold on;
plot(t,y2);
plot(t,y3);
--

==== 噪声信号

* 白噪声 : ``x=randn(1,n)``(1:表示一维数据，n:表示生成 n 个点)

* 均匀噪声 : ``x=rand(1,n)``(1:表示一维数据，n:表示生成 n 个点)

[TIP]
----
工程应用中**白噪声**居多。
----

.噪声
[source,matlab]
--
y1=randn(1,256);
y2=rand(1,256);
plot(y1);
hold on;
plot(y2);
--

==== 其他信号

* 脉冲信号
* 阶跃信号(脉冲信号积分)
* 斜坡信号(阶跃信号积分)
* 加速度信号(斜坡信号积分)

.其他信号demo
[source,matlab]
--
% 脉冲信号
t = linspace(0,1,101)
y=[zeros(1,50),1,zeros(1,50)];
plot(t,y)

% 阶跃信号
t = linspace(0,1,101);
y=[zeros(1,50),ones(1,51)];
plot(t,y);
ylim([0 1.25])

% 斜坡信号
y = linspace(0,10,101)
plot(y);
--

=== 信号发生器设计··

信号的包络、泛音；

* 信号的幅值调制（包络）**反映高频信号幅度变化的曲线**
+
**基音**：一般的声音都是由发音体发出的一系列频率、振幅各不相同的振动复合而成的。
这些振动中有一个频率**最低**的振动，由它发出的音就是**基音**。
乐器的按键频率是多少，指的就是基音的频率，基音决定了音高。
+
**泛音**：乐器振动时，其振动频率并不是单一的。只有基音的声音，听起来有强烈的人工感觉。
琴弦发声时，除基音外，还有不同的**基音频率倍数的成分**，称为**泛音**。

== 3. 信号的时域分析

== 4. 信号的频谱分析

== 5. 信号的时差域相关分析

== 6. 信号的幅值域分析

== 7. 信号的数字滤波技术

== 8. 信号的时-频分析技术
