= 数字信号处理

== 1. 计算机测量仪器系统

=== 计算机测量仪器

**计算机测量仪器**(虚拟仪器)是通过计算机作为仪器主体。
传感器经过放大和信号采集后，通过数据总线传输到计算机中，再由计算机软件进行分析、显示。

=== A/D 转换(ADC)

A/D 转换即模数转换，将模拟信号转换成数字信号。

ADC 类型：

* 积分型
* 逐次逼近型
* 并行比较型
* 串并型

ADC 主要参数：

. 转换器位数(精度)
. 转换时间(采样频率)
. 电压输入范围： `0~5v` `0~10v` `+/-5v` `+/-10v`

=== D/A 转换(DAC)

D/A 转换即数模转换，将数字信号转换成模拟信号。

DAC 主要参数：

. 转换器位数(精度)
. 转换时间(频率)
. 电压输出范围： `0~5v` `0~10v` `+/-5v` `+/-10v`

=== 采样定理

在计算机化测量系统中，**采样**就是将连续的传感器模拟信号，通过 ADC 转换为计算机能够分析的离散数字量。

**采样**是将离散**脉冲序列**与信号**相乘**，取离散点值的过程：

``p(t) * x(t)``

* 脉冲信号 p(t)
* 连续信号 x(t)

采样定理(Nyquist-Shannon)：
为保证采集后信号能真实地保留原始模拟信号信息，信号采样频率必须至少为原信号中最高频率成分的 2 倍，即 ``Fs > 2 Fmax`` 。

在工程领域，为保证采样信号质量： ``Fs > 5 Fmax``

[TIP]
--
**采样过程中的频率混叠**

频率混叠是采样频率不满足采样定理时，信号中的高频成分被不正确的采样成低频成分。

频率混叠是信号离散采样所引起的一个特有现象和重要概念。

例如： 1.5KHz 采样频率对 2KHz 的正弦信号进行采样时，输出是一个 500Hz 正弦信号。
--

当采样信号没有发生频率混叠时，采样信号频谱不发生重叠；
当采样信号发生频谱混叠时，采样信号频谱发生重叠。

在实际工程应用中为了放置发生频率混叠，通常在 ADC 采样前添加**低通滤波器(``0~Fs/2``)**实现添加抗混迭滤波。

Example: 声卡采集信号——AD变换
[source,matlab]
--
Fs = 11025;             % 采样频率
N= 44100;               % 采样长度
t = [0:N-1]/N;          % 采样时长
x = wavrecord(N, Fs);   % 声卡采样
plot(t, x);             % 图形绘制
set(gca,'color',[0.95, 0.95, 0.95]);
--

Example: 声卡食输出标准信号——DA变换
[source,matlab]
--
Fs = 44100;                             % 信号采样频率
dt = 1.0 / Fs;                          % 采样间隔
T = 2;                                  %
N = T / dt;                             %
t = [0: N - 1]/N;                       %
x = 0.3*sin(2*pi*600*t);                %
plot(t,x);
axis([0, 0.01, -0.5, 0.5]);
wavplay(x,Fs);
set(gca,'color',[0.95,0.95,0.95]);
--

== 2. 信号函数与标准信号

== 3. 信号的时域分析

== 4. 信号的频谱分析

== 5. 信号的时差域相关分析

== 6. 信号的幅值域分析

== 7. 信号的数字滤波技术

== 8. 信号的时-频分析技术
