@startuml
[*] --> NEW : instantiate

NEW --> Active : start

state Active {
  RUNNING --> RUNNABLE : yield/schedule swap
  RUNNABLE --> RUNNING : thread was selected by scheduler
}

Active --> BLOCKED : suspend/sleep/wait
BLOCKED --> Active : resume/notify/notifyAll
BLOCKED --> TERMINATED : stop
Active --> TERMINATED : stop

TERMINATED --> [*]
@enduml