version: '2'
services:
  kafka1:
    image: docker.io/bitnami/kafka:3.1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/kafka1"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
  #      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183

  kafka2:
    image: docker.io/bitnami/kafka:3.1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9093:9092"
    volumes:
      - "kafka_data:/kafka2"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
#      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183

  kafka3:
    image: docker.io/bitnami/kafka:3.1
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "9094:9092"
    volumes:
      - "kafka_data:/kafka3"
    environment:
      KAFKA_LOG_DIRS: /kafka
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
  #      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183

  zoo1:
    image: docker.io/bitnami/zookeeper:3.8
    environment:
      MYID: 1
      SERVERS: zoo1,zoo2,zoo3
      ALLOW_ANONYMOUS_LOGIN: yes
    ports:
      - "2181:2181"
      - "2888"
      - "3888"
    volumes:
      - "zookeeper_data:/zoo1"

#  zoo2:
#    image: docker.io/bitnami/zookeeper:3.8
#    environment:
#      MYID: 2
#      SERVERS: zoo1,zoo2,zoo3
#      ALLOW_ANONYMOUS_LOGIN: yes
#    ports:
#      - "2182:2181"
#      - "2888"
#      - "3888"
#    volumes:
#      - "zookeeper_data:/zoo2"
#
#  zoo3:
#    image: docker.io/bitnami/zookeeper:3.8
#    environment:
#      MYID: 3
#      SERVERS: zoo1,zoo2,zoo3
#      ALLOW_ANONYMOUS_LOGIN: yes
#    ports:
#      - "2183:2181"
#      - "2888"
#      - "3888"
#    volumes:
#      - "zookeeper_data:/zoo3"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
